### ISSUE TITLE
Add a "Select all" checkbox

### ISSUE THREAD

**Issue by SiR-DanieL** [Automattic/woocommerce-connect-client#296] opened 2016-05-06 06:51 UTC
Can we add a "Select All" checkbox for each section in the rates?

![](http://cld.wthms.co/1krKj/5d4NGVG5+)

Like near the toggle arrow, or inside the section.

**Comment by jkudish** [comment] 2016-05-06 15:54
Duplicate of #198

**Closed by jkudish** 2016-05-06 15:54 UTC
Labels: [Type] Enhancement
