### ISSUE TITLE
Display units (e.g. in, cm, etc) in Inner and Outer Dimension prompts

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#352] opened 2016-05-20 18:01 UTC
Right now, I don't know if I'm entering in inches, centimeters, etc.

<img width="1081" alt="screen shot 2016-05-20 at 10 58 58 am" src="https://cloud.githubusercontent.com/assets/1595739/15437110/281794b0-1e7a-11e6-9aaa-e4a7496e0c34.png">

**Comment by nabsul** [comment] 2016-05-24 21:49
Duplicate of #358

**Closed by nabsul** 2016-05-24 21:49 UTC
Labels: Packages, [Pri] Normal, [Type] Bug
